# Generated by Django 6.0.6 on 2026-07-22 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Minha nota', max_length=120)),
                ('itens', models.JSONField(blank=True, default=list)),
                ('itens_concluidos', models.JSONField(blank=True, default=list)),
                ('pos_x', models.IntegerField(default=24)),
                ('pos_y', models.IntegerField(default=120)),
                ('fixada', models.BooleanField(default=False)),
                ('visivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
