# Generated by Django 6.0.6 on 2026-07-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
